{{- if and .Values.webhook.enabled .Values.webhook.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "peerdb-operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "peerdb-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "peerdb-operator.fullname" . }}-webhook-certs
  dnsNames:
    - {{ include "peerdb-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "peerdb-operator.fullname" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: {{ .Values.webhook.certManager.issuerRef.kind }}
    name: {{ .Values.webhook.certManager.issuerRef.name }}
{{- end }}
