# This rule is not used by the project peerdb-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to peerdb.peerdb.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: peerdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: peerdbsnapshotpool-viewer-role
rules:
- apiGroups:
  - peerdb.peerdb.io
  resources:
  - peerdbsnapshotpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - peerdb.peerdb.io
  resources:
  - peerdbsnapshotpools/status
  verbs:
  - get
