# This rule is not used by the project peerdb-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over peerdb.peerdb.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: peerdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: peerdbsnapshotpool-admin-role
rules:
- apiGroups:
  - peerdb.peerdb.io
  resources:
  - peerdbsnapshotpools
  verbs:
  - '*'
- apiGroups:
  - peerdb.peerdb.io
  resources:
  - peerdbsnapshotpools/status
  verbs:
  - get
